[pytest]
testpaths = tests --slowmo=200
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --headed --browser=chromium --html=reports/report.html --self-contained-html --disable-warnings --tracing=on